{% set name = "ariba" %}
{% set version = "2.9.3" %}
{% set md5 = "4576053069fb8c607f2e621e15891fbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/sanger-pathogens/{{ name }}/archive/v{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  skip: True # [py27]
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - dendropy >=4.2.0
    - pyfastaq >=3.12.0
    - pysam >=0.9.1
    - pymummer >=0.10.2
    - beautifulsoup4 >=4.1.0
    - matplotlib
    - gcc  # [not osx]
    - llvm  # [osx]
    - zlib

  run:
    - python
    - dendropy >=4.2.0
    - pyfastaq >=3.12.0
    - pysam >=0.9.1
    - pymummer >=0.10.2
    - bowtie2 >=2.1.0
    - cd-hit >=4.6
    - samtools >=1.2
    - bcftools >=1.2
    - mummer >=3.23
    - libgcc  # [not osx]
    - zlib

test:
  imports:
    - ariba
    - ariba.tasks

  requires:
    - nose >=1.3

about:
  home: https://github.com/sanger-pathogens/ariba
  license: GNU General Public License v3 (GPLv3)
  summary: 'ARIBA: Antibiotic Resistance Identification By Assembly'
