{% set name = "seroba" %}
{% set version = "0.1.5" %}
{% set hash = "91ababdf896b849e71e3d09f134a87b4a8eb17b14caa5bcf556993b07e80ba0f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/a9/cf/b21734ec5736af98db3ad82e05d130e28872931315e0150757c99d6b460d/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  skip: True # [py27]
  number: 0

requirements:
  build:
    - python
    - setuptools
    - ariba >=2.9.1

  run:
    - python
    - kmc >=3.0.0
    - ariba >=2.9.1
    - pyyaml >=3.12
    - pymummer >=0.10.2
    - biopython >=1.68

test:
  imports:
    - seroba
    - seroba.tasks

  requires:
    - nose >=1.3

about:
  home: https://github.com/sanger-pathogens/seroba
  license: GNU General Public License v3 (GPLv3)
  summary: 'SeroBA is an in silico serotyping tool for Streptococcus pneumoniae'
